Rewrite nodetool script to simplify the release script.

diff --git a/src/rel/files/cloudi.in b/src/rel/files/cloudi.in
--- a/src/rel/files/cloudi.in
+++ b/src/rel/files/cloudi.in
@@ -18,37 +18,41 @@ PROGNAME_FILE="$ROOT_BIN_DIR/$PROGNAME"
 VMARGS_FILE="$ROOT_ETC_DIR/vm.args"
 ERLCONFIG_FILE="$ROOT_ETC_DIR/app.config"
 
-# Extract arguments from vm.args
-NODE_NAME_ARG=`egrep '^-s?name' $VMARGS_FILE`
-if [ -z "$NODE_NAME_ARG" ]; then
-    echo "vm.args needs to have either -name or -sname parameter."
-    exit 1
-fi
-NODE_COOKIE_ARG=`grep '^-setcookie' $VMARGS_FILE`
-if [ -z "$NODE_COOKIE_ARG" ]; then
-    echo "vm.args needs to have a -setcookie parameter."
-    exit 1
-fi
+# based on TIMEOUT_TERMINATE_MAX in cloudi_core_i_constants.hrl (milliseconds)
+SHUTDOWN_TIME_MAX=65000
 
-# Create nodetool arguments
-NODETOOL="$BINDIR/escript $ROOT_BIN_DIR/nodetool $NODE_NAME_ARG $NODE_COOKIE_ARG"
+# Create epmd command-line
+EPMD="$BINDIR/epmd -daemon"
+
+# Create nodetool command-line
+NODETOOL="$BINDIR/escript $ROOT_BIN_DIR/nodetool"
+
+# Common erl command-line arguments enforced on any vm.args file use
+VMARGS="-mode embedded -shutdown_time $SHUTDOWN_TIME_MAX"
 
 # Deployment environment files
 if [ -z "$TMPDIR" ]; then
     TMPDIR="/tmp"
 fi
 PIPE_DIR="$TMPDIR/$PROGNAME/"
-if [ -z "$PID_FILE" ]; then
-    PID_FILE="$ROOT_LOG_DIR/$PROGNAME.pid"
+if [ -z "$CLOUDI_PID_FILE" ]; then
+    CLOUDI_PID_FILE="$ROOT_LOG_DIR/$PROGNAME.pid"
 fi
 
 cd "$ROOTDIR"
 
+# Ensure epmd is running
+$EPMD
+if [ $? -ne 0 ]; then
+    echo "EPMD failed to start!"
+    exit 1
+fi
+
 case "$1" in
     start|start_boot)
         # Make sure there is not already a node running
-        PONG=`$NODETOOL ping`
-        if [ "$PONG" = "pong" ]; then
+        $NODETOOL test
+        if [ $? -eq 0 ]; then
             echo "Node is already running!"
             exit 1
         fi
@@ -91,7 +95,6 @@ case "$1" in
         mkdir -p "$PIPE_DIR"
         $BINDIR/run_erl -daemon "$PIPE_DIR" "$ROOT_LOG_DIR" "exec $PROGNAME_FILE $START_OPTION $RUN_PARAM" 2>&1
         ;;
-
     stop)
         # Wait for the node to completely stop...
         $NODETOOL stop
@@ -99,66 +102,53 @@ case "$1" in
         if [ $EXIT -ne 0 ]; then
             exit $EXIT
         fi
-        if [ ! -f "$PID_FILE" ]; then
+        if [ ! -f "$CLOUDI_PID_FILE" ]; then
             exit 1
         fi
-        PID=`cat "$PID_FILE"`
+        PID=`cat "$CLOUDI_PID_FILE"`
         while `kill -0 "$PID" 2>/dev/null`;
         do
             sleep 1
         done
         ;;
-
     restart)
         ## Restart the VM without exiting the process
         $NODETOOL restart
         exit $?
         ;;
-
     reboot)
         ## Restart the VM completely (uses heart to restart it)
         $NODETOOL reboot
         exit $?
         ;;
-
     ping)
         ## See if the VM is alive
         $NODETOOL ping
         exit $?
         ;;
-
     attach)
         # Make sure a node IS running
-        PONG=`$NODETOOL ping`
-        EXIT=$?
-        if [ $EXIT -ne 0 ]; then
+        $NODETOOL test
+        if [ $? -ne 0 ]; then
             echo "Node is not running!"
-            exit $EXIT
+            exit 1
         fi
 
         shift
-        exec $BINDIR/to_erl "$PIPE_DIR"
+        exec "$BINDIR/to_erl" "$PIPE_DIR"
         ;;
-
     remote_console)
         # Make sure a node IS running
-        PONG=`$NODETOOL ping`
-        EXIT=$?
-        if [ $EXIT -ne 0 ]; then
+        REMSH=`$NODETOOL args_remsh`
+        if [ $? -ne 0 ]; then
             echo "Node is not running!"
-            exit $EXIT
+            exit 1
         fi
-        
-        # Create remsh arguments
-        REMSH_TYPE=`echo $NODE_NAME_ARG | awk '{print $1}'`
-        REMSH_NAME=`echo $NODE_NAME_ARG | awk '{print $2}'`
-        REMSH_NODE_NAME_ARG="$REMSH_TYPE remsh`date +%s`@`echo $REMSH_NAME | awk -F@ '{print $2}'`"
-        REMSH="$BINDIR/erl $REMSH_NODE_NAME_ARG -remsh $REMSH_NAME $NODE_COOKIE_ARG"
+        CMD="$BINDIR/erl $REMSH"
 
         shift
-        exec $REMSH
+        exec $CMD
         ;;
-
     console|console_clean|console_boot)
         # .boot file typically just $PROGNAME (ie, the app name)
         # however, for debugging, sometimes start_clean.boot is useful.
@@ -173,7 +163,7 @@ case "$1" in
                 ;;
         esac
         # Setup beam-required vars
-        CMD="$BINDIR/erlexec -boot $RELEASEDIR/$BOOTFILE -mode embedded -config $ERLCONFIG_FILE -args_file $VMARGS_FILE"
+        CMD="$BINDIR/erlexec -boot $RELEASEDIR/$BOOTFILE -config $ERLCONFIG_FILE -args_file $VMARGS_FILE $VMARGS"
         export EMU
         export ROOTDIR
         export BINDIR
@@ -184,19 +174,18 @@ case "$1" in
         echo "Root: $ROOTDIR"
 
         # Store the pid
-        echo $$ > "$PID_FILE"
+        echo $$ > "$CLOUDI_PID_FILE"
 
         # Start the VM
         exec $CMD -- ${1+"$@"}
         ;;
-
     foreground)
         # start up the release in the foreground for use by runit
         # or other supervision services
         FOREGROUNDOPTIONS="-noinput +Bd"
 
         # Setup beam-required vars
-        CMD="$BINDIR/erlexec $FOREGROUNDOPTIONS -boot $RELEASEDIR/$PROGNAME -config $ERLCONFIG_FILE -args_file $VMARGS_FILE"
+        CMD="$BINDIR/erlexec $FOREGROUNDOPTIONS -boot $RELEASEDIR/$PROGNAME -config $ERLCONFIG_FILE -args_file $VMARGS_FILE $VMARGS"
         export EMU
         export ROOTDIR
         export BINDIR
@@ -207,7 +196,7 @@ case "$1" in
         echo "Root: $ROOTDIR"
 
         # Not using the pid file
-        rm -f "$PID_FILE"
+        rm -f "$CLOUDI_PID_FILE"
 
         # Start the VM
         exec $CMD -- ${1+"$@"}
