Update the release scripts for use without autoconf/automake in the examples hello_world_reltool and hello_world_embedded.

diff --git a/examples/hello_world_embedded/cloudi_hello_world_embedded b/examples/hello_world_embedded/cloudi_hello_world_embedded
--- a/examples/hello_world_embedded/cloudi_hello_world_embedded
+++ b/examples/hello_world_embedded/cloudi_hello_world_embedded
@@ -1,82 +1,58 @@
 #!/bin/sh
-# -*- tab-width:4;indent-tabs-mode:nil -*-
-# ex: ts=4 sw=4 et
+#-*-Mode:sh;coding:utf-8;tab-width:4;c-basic-offset:4;indent-tabs-mode:()-*-
+# ex: set ft=sh fenc=utf-8 sts=4 ts=4 sw=4 et nomod:
+
+# script location
+SCRIPT=`basename $0`
+SCRIPT_PATH=`dirname $0`
 
 # Name of the running pid (argv[0])
-PID_NAME=cloudi_hello_world_embedded
+PID_NAME="$SCRIPT"
+# Name of this file
+PROGNAME="$SCRIPT"
 
-# Script defaults
-SCRIPT=`basename $0`
-SCRIPT_DIR=`dirname $0`
-RUNNER_SCRIPT_DIR=`cd $SCRIPT_DIR && pwd`
-RUNNER_BASE_DIR=`dirname $RUNNER_SCRIPT_DIR`
-RUNNER_ETC_DIR="$RUNNER_BASE_DIR/etc"
-RUNNER_LOG_DIR="$RUNNER_BASE_DIR/logs"
+ROOTDIR=`cd $SCRIPT_PATH/.. && pwd`
+START_ERL_DATA="$ROOTDIR/releases/start_erl.data"
+ERLANG_ERTS_VERSION=`cat $START_ERL_DATA | awk '{print $1}'`
+RELEASE_VERSION=`cat $START_ERL_DATA | awk '{print $2}'`
+BINDIR="$ROOTDIR/erts-$ERLANG_ERTS_VERSION/bin"
+EMU=beam
+RELEASEDIR="$ROOTDIR/releases/$RELEASE_VERSION"
+ROOT_BIN_DIR="$ROOTDIR/bin"
+ROOT_ETC_DIR="$ROOTDIR/etc"
+ROOT_LOG_DIR="$ROOTDIR/logs"
+PROGNAME_FILE="$ROOT_BIN_DIR/$PROGNAME"
+VMARGS_FILE="$ROOT_ETC_DIR/vm.args"
+ERLCONFIG_FILE="$ROOT_ETC_DIR/app.config"
+PIPE_DIR="/tmp/$PROGNAME/"
+CLOUDI_PID_FILE="$ROOT_LOG_DIR/$PROGNAME.pid"
 
-# Make sure this script is running as the appropriate user
-RUNNER_USER=
-if [ ! -z "$RUNNER_USER" ] && [ `whoami` != "$RUNNER_USER" ]; then
-    exec sudo -u $RUNNER_USER -i $0 $@
-fi
+# based on TIMEOUT_TERMINATE_MAX in cloudi_core_i_constants.hrl (milliseconds)
+SHUTDOWN_TIME_MAX=65000
 
-# Make sure log directory exists
-mkdir -p $RUNNER_LOG_DIR
+# Create epmd command-line
+EPMD="$BINDIR/epmd -daemon"
 
-# Parse out release and erts info
-START_ERL=`cat $RUNNER_BASE_DIR/releases/start_erl.data`
-ERTS_VSN=${START_ERL% *}
-APP_VSN=${START_ERL#* }
+# Create nodetool command-line
+NODETOOL="$BINDIR/escript $ROOT_BIN_DIR/nodetool"
 
-VMARGS_PATH="$RUNNER_ETC_DIR/vm.args"
-CONFIG_PATH="$RUNNER_ETC_DIR/app.config"
+# Common erl command-line arguments enforced on any vm.args file use
+VMARGS="-mode embedded -shutdown_time $SHUTDOWN_TIME_MAX"
 
-# Note the trailing slash on $PIPE_DIR/
-PIPE_DIR_NAME=`basename $RUNNER_SCRIPT_DIR`
-PIPE_DIR="/tmp/$PIPE_DIR_NAME/"
+cd "$ROOTDIR"
 
-# Store the current pid in the log directory
-PID_FILE="$RUNNER_LOG_DIR/cloudi.pid"
-
-# Extract the target node name from node.args
-NAME_ARG=`egrep '^-s?name' $VMARGS_PATH`
-if [ -z "$NAME_ARG" ]; then
-    echo "vm.args needs to have either -name or -sname parameter."
+# Ensure epmd is running
+$EPMD
+if [ $? -ne 0 ]; then
+    echo "EPMD failed to start!"
     exit 1
 fi
 
-# Extract the name type and name from the NAME_ARG for REMSH
-REMSH_TYPE=`echo $NAME_ARG | awk '{print $1}'`
-REMSH_NAME=`echo $NAME_ARG | awk '{print $2}'`
-
-# Note the `date +%s`, used to allow multiple remsh to the same node transparently
-REMSH_NAME_ARG="$REMSH_TYPE remsh`date +%s`@`echo $REMSH_NAME | awk -F@ '{print $2}'`"
-REMSH_REMSH_ARG="-remsh $REMSH_NAME"
-
-# Extract the target cookie
-COOKIE_ARG=`grep '^-setcookie' $VMARGS_PATH`
-if [ -z "$COOKIE_ARG" ]; then
-    echo "vm.args needs to have a -setcookie parameter."
-    exit 1
-fi
-
-# Make sure CWD is set to the right dir
-cd $RUNNER_BASE_DIR
-
-# Add ERTS bin dir to our path
-ERTS_PATH="$RUNNER_BASE_DIR/erts-$ERTS_VSN/bin"
-
-# Setup command to control the node
-NODETOOL="$ERTS_PATH/escript $ERTS_PATH/nodetool $NAME_ARG $COOKIE_ARG"
-
-# Setup remote shell command to control node
-REMSH="$ERTS_PATH/erl $REMSH_NAME_ARG $REMSH_REMSH_ARG $COOKIE_ARG"
-
-# Check the first argument for instructions
 case "$1" in
     start|start_boot)
         # Make sure there is not already a node running
-        RES=`$NODETOOL ping`
-        if [ "$RES" = "pong" ]; then
+        $NODETOOL test
+        if [ $? -eq 0 ]; then
             echo "Node is already running!"
             exit 1
         fi
@@ -92,110 +68,90 @@ case "$1" in
                 HEART_OPTION="start_boot"
                 ;;
         esac
-        # Default CloudI run_erl logging settings
-        if [ -z "$RUN_ERL_LOG_ALIVE_MINUTES" -a \
-             -z "$RUN_ERL_LOG_ACTIVITY_MINUTES" -a \
-             -z "$RUN_ERL_LOG_ALIVE_IN_UTC" ]; then
-            RUN_ERL_LOG_ALIVE_MINUTES="15"      # 15 minutes (default)
-            RUN_ERL_LOG_ACTIVITY_MINUTES="5"    # 5 minutes (default)
-            RUN_ERL_LOG_ALIVE_IN_UTC="1"
-            export RUN_ERL_LOG_ALIVE_MINUTES
-            export RUN_ERL_LOG_ACTIVITY_MINUTES
-            export RUN_ERL_LOG_ALIVE_IN_UTC
-        fi
-        if [ -z "$RUN_ERL_LOG_GENERATIONS" -a \
-             -z "$RUN_ERL_LOG_MAXSIZE" ]; then
-            RUN_ERL_LOG_GENERATIONS="128"       # from app.config sasl env
-            RUN_ERL_LOG_MAXSIZE="536870912"     # from app.config sasl env
-            export RUN_ERL_LOG_GENERATIONS
-            export RUN_ERL_LOG_MAXSIZE
-        fi
+        # CloudI run_erl logging settings
+        export RUN_ERL_LOG_ACTIVITY_MINUTES="5"    # 5 minutes (default)
+        export RUN_ERL_LOG_ALIVE_MINUTES="15"      # 15 minutes (default)
+        export RUN_ERL_LOG_ALIVE_IN_UTC="1"
+        export RUN_ERL_LOG_ALIVE_FORMAT="%Y-%m-%dT%H:%M:%SZ"
+        export RUN_ERL_LOG_GENERATIONS="128"
+        export RUN_ERL_LOG_MAXSIZE="536870912"
+        export RUN_ERL_DISABLE_FLOWCNTRL="true"
         # OS process name created by run_erl
         export ESCRIPT_NAME="$PID_NAME"
 
         RUN_PARAM="'$@'"
-        HEART_COMMAND="$RUNNER_BASE_DIR/bin/$SCRIPT $HEART_OPTION $RUN_PARAM"
-        export HEART_COMMAND
-        mkdir -p $PIPE_DIR
-        $ERTS_PATH/run_erl -daemon $PIPE_DIR $RUNNER_LOG_DIR "exec $RUNNER_BASE_DIR/bin/$SCRIPT $START_OPTION $RUN_PARAM" 2>&1
+        export HEART_COMMAND="$PROGNAME_FILE $HEART_OPTION $RUN_PARAM"
+        mkdir -p "$PIPE_DIR"
+        $BINDIR/run_erl -daemon "$PIPE_DIR" "$ROOT_LOG_DIR" "exec $PROGNAME_FILE $START_OPTION $RUN_PARAM" 2>&1
         ;;
-
     stop)
         # Wait for the node to completely stop...
         $NODETOOL stop
-        ES=$?
-        if [ "$ES" -ne 0 ]; then
-            exit $ES
+        EXIT=$?
+        if [ $EXIT -ne 0 ]; then
+            exit $EXIT
         fi
-        if [ ! -f "$PID_FILE" ]; then
+        if [ ! -f "$CLOUDI_PID_FILE" ]; then
             exit 1
         fi
-        PID=`cat $PID_FILE`
-        while `kill -0 $PID 2>/dev/null`;
+        PID=`cat "$CLOUDI_PID_FILE"`
+        while `kill -0 "$PID" 2>/dev/null`;
         do
             sleep 1
         done
-        ;;
 
+        # Remove the pid file
+        rm -f "$CLOUDI_PID_FILE"
+        ;;
     restart)
-        ## Restart the VM without exiting the process
+        # Restart the VM without exiting the process
         $NODETOOL restart
-        ES=$?
-        if [ "$ES" -ne 0 ]; then
-            exit $ES
-        fi
+        exit $?
         ;;
-
     reboot)
-        ## Restart the VM completely (uses heart to restart it)
+        # Restart the VM completely (uses heart to restart it)
         $NODETOOL reboot
-        ES=$?
-        if [ "$ES" -ne 0 ]; then
-            exit $ES
-        fi
+        exit $?
         ;;
-
+    test)
+        # Test if the VM is alive without any output
+        $NODETOOL test
+        exit $?
+        ;;
     ping)
-        ## See if the VM is alive
+        # See if the VM is alive
         $NODETOOL ping
-        ES=$?
-        if [ "$ES" -ne 0 ]; then
-            exit $ES
-        fi
+        exit $?
         ;;
-
     attach)
         # Make sure a node IS running
-        RES=`$NODETOOL ping`
-        ES=$?
-        if [ "$ES" -ne 0 ]; then
+        $NODETOOL test
+        if [ $? -ne 0 ]; then
             echo "Node is not running!"
-            exit $ES
+            exit 1
         fi
 
         shift
-        exec $ERTS_PATH/to_erl $PIPE_DIR
+        exec "$BINDIR/to_erl" "$PIPE_DIR"
         ;;
-
     remote_console)
         # Make sure a node IS running
-        RES=`$NODETOOL ping`
-        ES=$?
-        if [ "$ES" -ne 0 ]; then
+        REMSH=`$NODETOOL args_remsh`
+        if [ $? -ne 0 ]; then
             echo "Node is not running!"
-            exit $ES
+            exit 1
         fi
+        CMD="$BINDIR/erl $REMSH"
 
         shift
-        exec $REMSH
+        exec $CMD
         ;;
-
     console|console_clean|console_boot)
-        # .boot file typically just $SCRIPT (ie, the app name)
+        # .boot file typically just $PROGNAME (ie, the app name)
         # however, for debugging, sometimes start_clean.boot is useful.
         # For e.g. 'setup', one may even want to name another boot script.
         case "$1" in
-            console)        BOOTFILE=$SCRIPT ;;
+            console)        BOOTFILE=$PROGNAME ;;
             console_clean)  BOOTFILE=start_clean ;;
             console_boot)
                 shift
@@ -204,62 +160,47 @@ case "$1" in
                 ;;
         esac
         # Setup beam-required vars
-        ROOTDIR="$RUNNER_BASE_DIR"
-        BINDIR="$ROOTDIR/erts-$ERTS_VSN/bin"
-        EMU=beam
-        PROGNAME=`echo $0 | sed 's/.*\\///'`
-        CMD="$BINDIR/erlexec -boot $RUNNER_BASE_DIR/releases/$APP_VSN/$BOOTFILE -mode embedded -config $CONFIG_PATH -args_file $VMARGS_PATH"
+        CMD="$BINDIR/erlexec -boot $RELEASEDIR/$BOOTFILE -config $ERLCONFIG_FILE -args_file $VMARGS_FILE $VMARGS"
         export EMU
         export ROOTDIR
         export BINDIR
         export PROGNAME
 
-        # Dump environment info for logging purposes
+        # Dump the environment info to the console log
         echo "Exec: $CMD" -- ${1+"$@"}
         echo "Root: $ROOTDIR"
 
-        # Log the startup
-        logger -t "$SCRIPT[$$]" "Starting up"
-
         # Store the pid
-        echo $$ > $PID_FILE
+        echo $$ > "$CLOUDI_PID_FILE"
 
         # Start the VM
         exec $CMD -- ${1+"$@"}
         ;;
-
     foreground)
         # start up the release in the foreground for use by runit
         # or other supervision services
-
-        BOOTFILE="$SCRIPT"
         FOREGROUNDOPTIONS="-noinput +Bd"
 
         # Setup beam-required vars
-        ROOTDIR="$RUNNER_BASE_DIR"
-        BINDIR="$ROOTDIR/erts-$ERTS_VSN/bin"
-        EMU=beam
-        PROGNAME=`echo $0 | sed 's/.*\///'`
-        CMD="$BINDIR/erlexec $FOREGROUNDOPTIONS -boot $RUNNER_BASE_DIR/releases/$APP_VSN/$BOOTFILE -config $CONFIG_PATH -args_file $VMARGS_PATH"
+        CMD="$BINDIR/erlexec $FOREGROUNDOPTIONS -boot $RELEASEDIR/$PROGNAME -config $ERLCONFIG_FILE -args_file $VMARGS_FILE $VMARGS"
         export EMU
         export ROOTDIR
         export BINDIR
         export PROGNAME
 
-        # Dump environment info for logging purposes
+        # Dump the environment info to the console log
         echo "Exec: $CMD" -- ${1+"$@"}
         echo "Root: $ROOTDIR"
 
         # Not using the pid file
-        rm -f $PID_FILE
+        rm -f "$CLOUDI_PID_FILE"
 
         # Start the VM
         exec $CMD -- ${1+"$@"}
         ;;
     *)
-        echo "Usage: $SCRIPT {start|start_boot <file>|foreground|stop|restart|reboot|ping|console|console_clean|console_boot <file>|attach|remote_console}"
+        echo "Usage: $PROGNAME {start|start_boot <file>|foreground|stop|restart|reboot|test|ping|console|console_clean|console_boot <file>|attach|remote_console}"
         exit 1
         ;;
 esac
 
-exit 0
